name: 'xcresulttool'
description: 'generates a human-readable test report from the Xcode result bundle and shows it on GitHub Checks.'
author: 'kishikawa katsumi'
inputs:
  path:
    required: true
    description: 'Path to the xcresult bundle'
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
  title:
    description: 'Title for the check results'
    default: 'Xcode test results'
  show-passed-tests:
    description: 'Show passed tests'
    default: true
  show-code-coverage:
    description: 'Whether to show code coverage'
    default: true
  upload-bundles:
    description: 'Whether to upload the xcresult bundles. possible values: always, failure, never. Specifying failure will only upload the bundle if all the tests do not pass.'
    default: always
  hide-summary-table:
    description: 'Whether to hide the table with all test results in the Summary section'
    default: false
  hide-passed-tests-from-details:
    description: 'Whether to hide passed tests in the Details section'
    default: false
  format-attachments-table:
    description: 'Whether to format attachments as a table'
    default: false
  attachments-table-header:
    description: Comma separated list of titles for the attachments table header. Used only if it's an exact match with number of attachments. Valid only in case format-attachments-table is also true.
    default: 'Expected, Actual, Difference'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'blue'
